### ISSUE TITLE
shasum bundled with sqitch is broken

### ISSUE THREAD

**Issue by jhogendorn** [theory/homebrew-sqitch#36]
"$errmsg" is not exported by the Digest::SHA module
    Can't continue after import errors at /usr/local/bin/shasum line 24.
    BEGIN failed--compilation aborted at /usr/local/bin/shasum line 24.

i get this on switching to a directory managed by git, it seems sqitch is providing its own (broken) shasum binary:

    % which -a shasum
    /usr/local/bin/shasum
    /usr/local/bin/shasum
    /usr/bin/shasum

    % ls -lah /usr/local/bin/shasum
    lrwxr-xr-x  1 jhogendorn  admin    47B Feb  4 16:35 /usr/local/bin/shasum -> ../Cellar/sqitch_dependencies/0.9996/bin/shasum

I've 'fixed' this by removing the link for the sqitch binary, however thats a bandaid at best.

**Comment by theory** [comment]
It's not sqitch, it's the [Digest-SHA module](https://metacpan.org/release/Digest-SHA). And it's likely not broken, just has a different interface than Git expects.

**Comment by gurjeet** [comment]
I second @jhogendorn's concern. I was trying to install Nix package manager, and `shasum` packged with Sqitch was causing this same error. I had to uninstall `sqitch` as well as `sqitch_dependencies` to get over this error (essentially removing this incarnation of `shasum`).

I got my sqitch back by `nix-env -i sqitch-pg`, thoguh :-)

**Comment by theory** [comment]
As of v0.9998, there is a new Sqitch Homebrew formula that no longer installs the scripts that come with modules Sqitch depends on. It only installs `sqitch`, and only in its Cellar (plus the symlink, of course). So this should no longer be an issue.

I have no idea how Nix packages Sqitch, though; I wasn't even aware of it. I see it [here](/NixOS/nixpkgs/blob/56904d7c423f2b13b37fbd29f39bbb4b52bc7824/pkgs/development/tools/misc/sqitch/default.nix); looks like it only links `bin/sqitch` now, so that's good. Still, whoever maintains the Nix Sqitch package might want to look at the updated [Homebrew formula](/sqitchers/homebrew-sqitch/blob/master/Formula/sqitch.rb) and convert it to use bundling, support options for database engines. etc.
